-- Your SQL goes here

CREATE TABLE IF NOT EXISTS users (
	user_id     INTEGER NOT NULL PRIMARY KEY,
	hash		VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS pixel (
	pixel_id    INTEGER NOT NULL PRIMARY KEY,
	ts			TIMESTAMP NOT NULL,
	user_id		INTEGER NOT NULL REFERENCES users,
	color		INTEGER NOT NULL,
	x1			INTEGER NOT NULL,
	y1			INTEGER NOT NULL,
	x2			INTEGER,
	y2			INTEGER
);